### ISSUE TITLE
Feature request: random based on class, not object

### ISSUE THREAD

**Issue by gerchicov-bp** [jamesdouble/RandMyMod#6]
You pass an object into func but why not to allow to pass its type only?

**Comment by jamesdouble** [comment]
@gerchicov-bp thx for reply.

I only can figure out one way to get all variable type & name without pass object.

That is `RunTime` , but the type pass in must be `NSObject` or variable should declare `@dynamic `

That mean struct and other class not inherit from `NSObject` can't use it.

There are several way to approach (ex : Mirror)
